(source "gnu")
(source "melpa")

(package "lsp-grammarly" "0.2.2" "LSP Clients for Grammarly ")

(package-file "lsp-grammarly.el")

(depends-on "emacs" "27.1")
(depends-on "lsp-mode")
(depends-on "grammarly")
(depends-on "request")
(depends-on "s")
(depends-on "ht")

(setq network-security-level 'low      ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
      byte-compile-error-on-warn nil)
